gmtisp_src/appsinn/gmtisp_billing/urls.py
from django.conf import settings
from django.urls import path

from .views import (
    AccountActivationView,
    PlanListView,
    # BillingInfoCreateOrUpdateView,
    BillingInfoDeleteView,
    ChangePlanView,
    CreateOrderPlanChangeView,
    CreateOrderView,
    CurrentPlanView,
    InvoiceDetailView,
    OrderListView,
    OrderPaymentReturnView,
    OrderView,
    RedirectToBilling,
    UpgradePlanView,
    PaymentListView,
    PlanDetailView,
    PaymentDetailView,
    PaymentUpdateView,
    PaymentDeleteView,
    InvoiceListView,
    payment_success,
    payment_failed,
    paystack_initiate_payment,
    paystack_verify_payment,
    paystack_webhook_view
)


urlpatterns = [
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Plans
    path('account~activation/', AccountActivationView.as_view(), name='account_activation'),

    path('', PlanListView.as_view(), name='plans_list'),
    path('plan~details/<uuid:pk>/', PlanDetailView.as_view(), name='plan_details'),
    path('plan~current/', CurrentPlanView.as_view(), name='current_plan'),
    path('plan~upgrade/', UpgradePlanView.as_view(), name='upgrade_plan'),
    path('plan~change/<uuid:pk>/', ChangePlanView.as_view(), name='change_plan'),

    path('order~extend/<uuid:pk>/', CreateOrderView.as_view(), name='create_order_plan'),
    path('order~upgrade/<uuid:pk>/', CreateOrderPlanChangeView.as_view(), name='create_order_plan_change'),
    path('order~details/<uuid:pk>/', OrderView.as_view(), name='order'),

    path('orders~list/', OrderListView.as_view(), name='order_list'),
    path('order~/<uuid:pk>/payment~success/', OrderPaymentReturnView.as_view(status="success"), name='order_payment_success'),
    path('order~/<uuid:pk>/payment~failure/', OrderPaymentReturnView.as_view(status="failure"), name='order_payment_failure'),
    
    # path('billing~info/', BillingInfoCreateOrUpdateView.as_view(), name='billing_info'),
    path('billing~info/redirect/', RedirectToBilling.as_view(), name='redirect_to_billing'),
    path('billing~info/delete/', BillingInfoDeleteView.as_view(), name='billing_info_delete'),

    path('invoicse~list/', InvoiceListView.as_view(), name='invoice_list'),
    path('invoice~details/<uuid:pk>/', InvoiceDetailView.as_view(), name='invoice_preview_html'),

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ payment
    path('payments~list/', PaymentListView.as_view(), name='payment_list'),
    path('payments~update/<uuid:pk>/', PaymentUpdateView.as_view(), name='payment_update'),
    path('payments~delete/<uuid:pk>/', PaymentDeleteView.as_view(), name='payment_delete'),
    path('payment~details/<uuid:pk>/', PaymentDetailView.as_view(),name='payment_details'),

    path('payment/initiate/<uuid:order_id>/', paystack_initiate_payment, name='initiate_payment'),
    path('verify-payment/', paystack_verify_payment, name='verify_payment'),
    path('payment-success/', payment_success, name='payment_success'),
    path('payment-failed/', payment_failed, name='payment_failed'),
    path('webhook/paystack/', paystack_webhook_view, name='paystack_webhook'),

]

gmtisp_src/appsinn/openwisp_radius/urls.py
from django.urls import include, path

from .api.urls import get_api_urls
from .private_storage.urls import get_private_store_urls
from .saml.urls import get_saml_urls
from .social.urls import get_social_urls


def get_urls(api_views=None, social_views=None, saml_views=None):
    """
    Returns a list of urlpatterns
    Arguements:
        api_views(optional): views for Radius API
        social_view(optional): views for social login (if enabled)
        saml_views(optional): views for saml login (if enabled)
    """
    return [
        path('api/v1/', include(get_api_urls(api_views))),
        path('', include(get_private_store_urls())),
        path('radius/social-login/', include(get_social_urls(social_views))),
        path('radius/saml2/', include(get_saml_urls(saml_views))),
    ]


# Cannot used 'app_name' here because when the radius
# urls are not registered, yet we want to get url reverse
# using urlconf we still want radius to be our namespace.
namespace = 'radius'
urlpatterns = [path('', include((get_urls(), namespace), namespace=namespace))]

gmtisp_src/appsinn/openwisp_users/urls.py
from django.urls import path
from .views import (
    UserListView, UserDetailView, UserCreateView, UserUpdateView, UserDeleteView,
    OrganizationListView, OrganizationDetailView, OrganizationCreateView, OrganizationUpdateView, OrganizationDeleteView
)

urlpatterns = [
    path('', UserListView.as_view(), name='user_list'),
    path('user/<uuid:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('user/create/', UserCreateView.as_view(), name='user_create'),
    path('user/<uuid:pk>/update/', UserUpdateView.as_view(), name='user_update'),
    path('user/<uuid:pk>/delete/', UserDeleteView.as_view(), name='user_delete'),
    
    path('organizations/', OrganizationListView.as_view(), name='organization_list'),
    path('organization/<uuid:pk>/', OrganizationDetailView.as_view(), name='organization_detail'),
    path('organization/create/', OrganizationCreateView.as_view(), name='organization_create'),
    path('organization/<uuid:pk>/update/', OrganizationUpdateView.as_view(), name='organization_update'),
    path('organization/<uuid:pk>/delete/', OrganizationDeleteView.as_view(), name='organization_delete'),
]

gmtisp_src/gmtisp/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views.generic import TemplateView
from django.views import defaults as default_views

from appsinn.openwisp_radius.urls import get_urls

from . import views

if os.environ.get('SAMPLE_APP', False):
    """    
    If you are extending the API views or social views,
    please import them, otherwise pass `None` in place of these values'
    """
    from appsinn.openwisp_radius.api import views as api_views
    from appsinn.openwisp_radius.saml import views as saml_views
    from appsinn.openwisp_radius.social import views as social_views

    radius_urls = path(
        '', include((get_urls(api_views, social_views, saml_views), 'radius'))
    )
else:
    api_views = None
    social_views = None
    saml_views = None
    radius_urls = path('', include('openwisp_radius.urls'))


urlpatterns = [
    # path('', views.LoginView.as_view(), name="login"),
    # path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    # api urls
    path('api/v1/', include('openwisp_utils.api.urls')),
    path('api/v1/', include('openwisp_users.api.urls')),
    # path('api/v1/', include('gmtisp_billing.api.urls')),
    path('', include('openwisp_users.accounts.urls')),
    path('users/', include('openwisp_users.urls')),
    radius_urls,
    # path('captive-portal-mock/login/', views.captive_portal_login, name='captive_portal_login_mock'),
    # path('captive-portal-mock/logout/', views.captive_portal_logout, name='captive_portal_logout_mock'),
    # other urls
    path('testapp/', include('testing_app.urls')),
    path('testapp_api/', include('testing_app.api.urls')),
    path('billing/', include('gmtisp_billing.urls')),
    path('enduser/', include('gmtisp_enduser.urls')),

    path( 'menu-test-view/', TemplateView.as_view(template_name='testing_app/menu_test.html'), name='menu-test-view'),
    path('about/', TemplateView.as_view(template_name="gmtisp/pages/about.html"), name='about'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={"exception": Exception("Bad Request!")},),
        path('403/', default_views.permission_denied, kwargs={"exception": Exception("Permission Denied")},),
        path('404/', default_views.page_not_found, kwargs={"exception": Exception("Page not Found")},),
        path('500/', default_views.server_error),
    ]
     
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gmtisp_src/appsinn/gmtisp_billing/models.py
import logging

from django.db import models
from django.utils.translation import gettext_lazy as _

from swapper import swappable_setting

from .base.models import (
    AbstractBillingInfo,
    AbstractInvoice,
    AbstractOrder,
    AbstractPlan,
    AbstractPlanQuota,
    AbstractQuota,
    AbstractRecurringUserPlan,
    AbstractUserPlan,
    AbstractPayment,
)


logger = logging.getLogger(__name__)
# ----------------------------------------------------------- plans
class Plan(AbstractPlan):
    # Test existing fields can be modified
    default = models.BooleanField(
        help_text=AbstractPlan._meta.get_field('default').help_text,
        default=AbstractPlan._meta.get_field('default').default,
        null=True,
        blank=True,
    )

    class Meta(AbstractPlan.Meta):
        abstract = False
        swappable = swappable_setting('gmtisp_billing', 'Plan')


class UserPlan(AbstractUserPlan):
    class Meta(AbstractUserPlan.Meta):
        abstract = False
        swappable = swappable_setting('gmtisp_billing', 'UserPlan')


class RecurringUserPlan(AbstractRecurringUserPlan):
    class Meta(AbstractRecurringUserPlan.Meta):
        abstract = False
        swappable = swappable_setting('gmtisp_billing', 'RecurringUserPlan')


class Quota(AbstractQuota):
    class Meta(AbstractQuota.Meta):
        abstract = False
        swappable = swappable_setting('gmtisp_billing', 'Quota')


class PlanQuota(AbstractPlanQuota):
    class Meta(AbstractPlanQuota.Meta):
        abstract = False
        swappable = swappable_setting('gmtisp_billing', 'PlanQuota')


class BillingInfo(AbstractBillingInfo):
    class Meta(AbstractBillingInfo.Meta):
        abstract = False
        swappable = swappable_setting('gmtisp_billing', 'BillingInfo')


class Order(AbstractOrder):
    class Meta(AbstractOrder.Meta):
        abstract = False
        swappable = swappable_setting('gmtisp_billing', 'Order')


class Invoice(AbstractInvoice):
    class Meta(AbstractInvoice.Meta):
        abstract = False
        swappable = swappable_setting('gmtisp_billing', 'Invoice')


class Payment(AbstractPayment):
    class Meta(AbstractPayment.Meta):
        abstract = False
        swappable = swappable_setting('gmtisp_billing', 'Payment')

gmtisp_src/appsinn/gmtisp_billing/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.forms.widgets import HiddenInput
from django.utils.translation import gettext

from .utils import get_country_code
from .validators_my import max_plans_validator
from .models import Plan, Order, PlanQuota, BillingInfo, Payment


class PlanForm(forms.ModelForm):
    class Meta:
        model = Plan
        widgets = {'user' : HiddenInput,}
        exclude = ("user",)

    def clean(self):
        cleaned_data = super(PlanForm, self).clean()
        max_plans_validator(cleaned_data['user'], add=1)
        return cleaned_data


class OrderForm(forms.Form):
    plan_quota = forms.ModelChoiceField(
        queryset=PlanQuota.objects.all(), widget=HiddenInput, required=True
    )


class CreateOrderForm(forms.ModelForm):
    """
    This form is intentionally empty as all values for Order object creation need to be 
    computed inside view

    Therefore, when implementing for example a rabat coupons, you can add some fields here
     and create "recalculate" button.
    """

    class Meta:
        model = Order
        fields = tuple()


class BillingInfoForm(forms.ModelForm):
    class Meta:
        model = BillingInfo
        exclude = ("user",)

    def __init__(self, *args, request=None, **kwargs):
        ret_val = super().__init__(*args, **kwargs)
        if not self.instance.country:
            self.fields["country"].initial = get_country_code(request)
        return ret_val

    def clean(self):
        cleaned_data = super(BillingInfoForm, self).clean()

        try:
            cleaned_data["tax_number"] = BillingInfo.clean_tax_number(
                cleaned_data["tax_number"], cleaned_data.get("country", None)
            )
        except ValidationError as e:
            self._errors["tax_number"] = e.messages

        return cleaned_data


class BillingInfoWithoutShippingForm(BillingInfoForm):
    class Meta:
        model = BillingInfo
        exclude = (
            "user",
            "shipping_name",
            "shipping_street",
            "shipping_zipcode",
            "shipping_city",
        )


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['order', 'amount', 'currency', 'status', 'method']

gmtisp_src/appsinn/gmtisp_billing/api/views.py
from rest_framework import viewsets

from ..models import *
from .serializers import *


class PlanViewSet(viewsets.ModelViewSet):
    queryset = Plan.objects.all()
    serializer_class = PlanSerializer


class BillingInfoViewSet(viewsets.ModelViewSet):
    queryset = BillingInfo.objects.all()
    serializer_class = BillingInfoSerializer


class UserPlanViewSet(viewsets.ModelViewSet):
    queryset = UserPlan.objects.all()
    serializer_class = UserPlanSerializer


class RecurringUserPlanViewSet(viewsets.ModelViewSet):
    queryset = RecurringUserPlan.objects.all()
    serializer_class = RecurringUserPlanSerializer


class QuotaViewSet(viewsets.ModelViewSet):
    queryset = Quota.objects.all()
    serializer_class = QuotaSerializer


class PlanQuotaViewSet(viewsets.ModelViewSet):
    queryset = PlanQuota.objects.all()
    serializer_class = PlanQuotaSerializer


class OrderViewSet(viewsets.ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer


class InvoiceViewSet(viewsets.ModelViewSet):
    queryset = Invoice.objects.all()
    serializer_class = InvoiceSerializer


class PaymentViewSet(viewsets.ModelViewSet):
    queryset = Payment.objects.all()
    serializer_class = PaymentSerializer

gmtisp_src/appsinn/gmtisp_billing/templates/gmtisp_billing/plans/account_activation.html
{% extends 'gmtisp_billing/layout.html' %}
{% load i18n %}


{% block content %}
    <h4>{% if SUCCESSFUL %}{% trans "Activation successful" %}{% else %}{% trans "Activation failed" %}{% endif %}</h4>

    {% if SUCCESSFUL %}
        {#  include "partials/messages.html" #}
        {% blocktrans %}
            Your panels will be available again soon.
        {% endblocktrans %}
    {% else %}
        {% blocktrans %}
            Your account cannot by activated because your account exceeds plan limits. Please adjust usage of limits and then try to activate your account again.
        {% endblocktrans %}
        {%  include "partials/messages.html" %}
    {% endif %}

{% endblock %}

gmtisp_src/appsinn/gmtisp_billing/templates/gmtisp_billing/plans/current.html
{% extends 'gmtisp_billing/layout.html' %}
{% load i18n %}

{% block title %}
    {{ block.super }} | User Status
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            {% block plan_details %}
                <h3>{% trans "Plan details" %}</h3>
                {% include "gmtisp_billing/plans/plan_table.html" %}
            {% endblock %}
        </div>
        <div class="col-md-4">
            {% block account_details %}
                <h3>{% trans "Your account" %}</h3>
                <table class="table table-bordered">
                    <tr>
                        <td><strong>{% trans "Account" %}:</strong></td>
                        <td>{{ user }}</td>
                    </tr>
                    <tr>
                        <td><strong>{% trans "State" %}:</strong></td>
                        <td>
                            {% if userplan.active %}
                                {% trans "active" %}
                            {% else %}
                                {% trans "expired" %}
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td><strong>{% trans "Expire" %}:</strong></td>
                        <td>{{ userplan.expire }}</td>
                    </tr>
                    <tr>
                        <td><strong>{% trans "Plan" %}:</strong></td>
                        <td>
                            {{ userplan.plan }}
                            <a href="{% url 'upgrade_plan' %}">
                                <small>{% trans "upgrade" %}</small>
                            </a>
                        </td>
                    </tr>
                </table>
            {% endblock %}

            {% block need_more %}
                <h3>{% trans "Need more?" %}</h3>
                {% url 'upgrade_plan' as upgrade_url %}
                {% blocktrans %}
                    Please see other <a href="{{ upgrade_url }}"><small>currently available plans</small></a>.
                {% endblocktrans %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

gmtisp_src/appsinn/gmtisp_billing/templates/gmtisp_billing/plans/expiration_messages.html
{% load i18n %}


{% block expiration_messages %}
{% if ACCOUNT_EXPIRED %}

    <div class="h5 alert alert-danger">
        {% blocktrans with url=EXTEND_URL %}
            Your account has expired. Please <a href="{{ url }}">extend your account</a>.
        {% endblocktrans %}
    </div>
{% else %}

    {% if ACCOUNT_NOT_ACTIVE %}
        <div class="h5 alert alert-danger">
            {% blocktrans with url=ACTIVATE_URL %}
                Your account is not active. Possibly you are over some limits.
                Try to <a href="{{ url }}">activate your account</a>.
            {% endblocktrans %}
        </div>
    {% endif %}

    {% if EXPIRE_IN_DAYS >= 0 and EXPIRE_IN_DAYS <= 14 %}
        <div class="h5 alert alert-warning">
            {% blocktrans with extend_url=EXTEND_URL days_to_expire=EXPIRE_IN_DAYS %}
                Your account will expire soon (in {{ days_to_expire }} days).
                We recommend to <a href="{{ extend_url }}">extend your account now.</a>
            {% endblocktrans %}
        </div>
    {% endif %}

{% endif %}
{% endblock %}

gmtisp_src/appsinn/gmtisp_billing/templates/gmtisp_billing/plans/plan_list.html
{% extends 'gmtisp_billing/layout.html' %}
{% load i18n %}

{% block title %} Plan List {% endblock %}

{% block content %}
    {% block seo_title %}{% trans "PLAN LIST" %}{% endblock %}
    {% block 'table' %}
    <table class="table">
        <thead>
            <tr>
                <th>Plan Name</th>
                <th>Plan Type</th>
                <th>Plan Available</th>
                <th>Plan Visible</th>
                <th>Plan quotas</th>
                <th>Plan setup cost</th>
            </tr>
        </thead>
        <tbody>
            {% for plan in plans %}
            <tr>
                <td><a href="{% url 'plan_details' plan.pk %}">{{ plan.name }}</td>
                <td>{{ plan.plan_type }}</td>
                <td>{{ plan.available }}</td>
                <td>{{ plan.visible }}</td>
                <td>{{ plan.quotas.first }}</td>
                <td>{{ plan.plan_setup_cost }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endblock %}

    {% block pagination_second %}
    {% include "partials/pagination.html" %}
    {% endblock %}

{% endblock %}

gmtisp_src/appsinn/gmtisp_billing/templates/gmtisp_billing/plans/plan_table.html
{% load i18n %}

{% if request.user.is_authenticated %}
<div class="container">
    <div class="row">
      {% for plan in plan_list %}
        <div class="col-md-3 mb-4">
            <div class="card card-pricing card-pricing-focus card-primary">
                <div class="card-header">
                    <h4 class="card-title">{{ plan.name_for_users }}</h4>
                    <div class="card-price">
                        <span class="price"><small>₵</small>{{ plan.price }}</span>
                    </div>
                </div>
                <div class="card-body">
                    <ul class="specification-list">
                        <li>
                            <span class="name-specification">Start When</span>
                            <span class="status-specification">{{ plan.starts_when }}</span>
                        </li>
                        {% for plan_quota in plan.planquota_set.all %}
                          {% if plan_quota.quota.name %}
                            {% if plan_quota.quota.uptime_limit %}
                            <li>
                                <span class="name-specification">Validity</span>
                                <span class="status-specification">{{ plan_quota.quota.uptime_limit }}</span>
                            </li>
                            {% endif %}
                            {% if plan_quota.quota.transfer_limit %}
                            <li>
                                <span class="name-specification">Transfer Limit</span>
                                <span class="status-specification">{{ plan_quota.quota.transfer_limit }}</span>
                            </li>
                            {% endif %}

                              {% if plan_quota.quota.rate_limit_rx and plan_quota.quota.rate_limit_tx %}
                              <li>    
                                  <span class="name-specification">Rate Limit</span>
                                  <span class="status-specification">{{ plan_quota.quota.rate_limit_rx }} / {{ plan_quota.quota.rate_limit_tx }}</span>
                              </li>
                              {% endif %}
                              {% if plan_quota.quota.url %}
                                <a href="{{ plan_quota.quota.url }}" class="info_link quota">
                              {% endif %}
                            <li>
                              <span class="plan_description">{{ plan.description|default:"-" }}</span>
                            </li>
                            {% if plan_quota.pk %}
                              <a href="{% url 'create_order_plan' pk=plan_quota.pk %}" class="buy btn btn-info">{% trans "Buy Now" %}</a>
                            {% else %}
                              <span class="btn btn-secondary disabled">{% trans "Unavailable" %}</span>
                            {% endif %}
                          {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
      {% endfor %}
    </div>
</div>
{% else %}
    <p>Please log in to see available plans.</p>
{% endif %}

gmtisp_src/appsinn/gmtisp_billing/templates/gmtisp_billing/plans/plan_table2.html
{% for plan in plan_list %}
  <div class="row justify-content-center align-items-center">
    <div class="col-md-4 pl-md-0 pr-md-0">
      <div class="card card-pricing card-pricing-focus card-primary">
        <div class="card-header {% if forloop.counter0 == current_userplan_index %}current{% endif %}" style="background-color: {% if plan == userplan.plan %}#045daa{% else %}#04AA6D{% endif %}">
          <h4 class="card-title">Professional</h4>
          <div class="card-price">      
            {% if plan.url %}<a href="{{ plan.url }}" class="info_link plan">{% endif %}
            <span class="price">{{ plan.name }}</span>
            {% if plan == userplan.plan %}
            <sup style="font-size: 45%;">{% trans "Current plan" %}</sup>
            {% endif %}
            {% if plan.url %}</a>{% endif %}
          </div>
        </div>
        <div class="card-body">
          <ul class="specification-list">
            <li>
              <span class="name-specification plan_price planpricing_footer {% if forloop.counter0 == current_userplan_index %}current{% endif %}"> 
                {% if plan.available %}
                <ul>
                  {% if not plan.is_free %}
                    {% for plan_pricing in plan.planpricing_set.all %}
                      {% if plan_pricing.visible %}
                        <li>
                        {% if plan_pricing.pricing.url %}<a href="{{ plan_pricing.pricing.url }}" class="info_link pricing">{% endif %}
                          <span class="plan_pricing_name">{{ plan_pricing.pricing.name }}</span>
                          <span class="plan_pricing_period">({{ plan_pricing.pricing.period }} {% trans "days" %})</span>
                          {% if plan_pricing.pricing.url %}</a>{% endif %}
                          <span class="plan_pricing_price">{{ plan_pricing.price }}&nbsp;{{ CURRENCY }}</span>
                          {% if plan_pricing.plan == userplan.plan or userplan.is_expired or userplan.plan.is_free %}
                          <a href="{% url 'create_order_plan' pk=plan_pricing.pk %}" class="buy">{% trans "Buy" %}</a>
                        </li>
                        {% endif %}
                      {% endif %}
                    {% endfor %}
                  {% else %}
                    {# Allow selecting plans with no pricings #}
                    <li>
                        <span class="plan_pricing_name">{% trans "Free" %}</span>
                        <span class="plan_pricing_period">({% trans "no expiry" %})</span>
                        <span class="plan_pricing_price">0&nbsp;{{ CURRENCY }}</span>
                        {% if plan != userplan.plan or userplan.is_expired %}
                            <a href="{% url 'create_order_plan_change' pk=plan.id %}" class="change_plan">
                                {% if userplan.is_expired %}
                                    {% trans "Select" %}
                                {% else %}
                                    {% trans "Change" %}
                                {% endif %}
                            </a>
                        {% endif %}
                    </li>
                  {% endif %}

                {% else %}
                  <span class="plan_not_available">
                    {% url 'upgrade_plan' as upgrade_url %}
                    {% blocktrans %}
                        This plan is not available anymore and cannot be extended.<p>
                        You need to upgrade your account to any of <a href="{{ upgrade_url }}">currently available plans</a>.
                    {% endblocktrans %}
                  </span>

                {% endif %}   
              </span>
              <span class="status-specification">Yes</span>
            </li>
            {% if user.is_authenticated %}
            <li class="">
              <span class="name-specification">Expire</span>
                <span class="status-specification plan_price planpricing_footer {% if forloop.counter0 == current_userplan_index %}current{% endif %}"> 
                  {% if plan != userplan.plan and not userplan.is_expired and not userplan.plan.is_free %}
                    <a href="{% url 'create_order_plan_change' pk=plan.id %}" class="change_plan">{% trans "Change Plan" %}</a>
                  {% endif %}
                </span>
            </li>
            {% endif %}
            <li>
              <span class="name-specification">Quota</span>
              <span class="status-specification">
                {% for quota_row in plan_table %}
                  <th class="quota_header">
                    {% if quota_row.0.url %}<a href="{{ quota_row.0.url }}" class="info_link quota">{% endif %}
                    <span class="quota_name">{{ quota_row.0.name }}</span>
                    <span class="quota_description">{{ quota_row.0.description }}</span>
                    {% if quota_row.0.url %}</a>{% endif %}
                  </th>
                  {% for plan_quota in quota_row.1 %}
                    <td class="{% if forloop.counter0 == current_userplan_index %}current{% endif %}">
                      {% if plan_quota != None %}
                        {% if quota_row.0.is_boolean %}
                          {% if plan_quota.value %} + {% else %} - {% endif %}
                        {% else %}
                          {% if plan_quota.value == None %}{% trans 'no limit' %}{% else %}{{ plan_quota.value }} {{ quota_row.0.unit }}{% endif %}
                        {% endif %}
                      {% endif %}
                    </td>
                  {% endfor %}
                {% endfor %}
              </span>
            </li>
            <li>
              <span class="name-specification">{{ plan.description }}</span>
            </li>
            <li>
              <span class="name-specification">Live Support</span>
              <span class="status-specification">Yes</span>
            </li>
          </ul>
        </div>
        <div class="card-footer">
          <button class="btn btn-light btn-block"><b>Buy Now</b></button>
        </div>
      </div>
    </div>
  </div>
{% endfor %}